# Generated by Django 5.2.5 on 2025-08-28 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blizzgame', '0029_dispute_disputemessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='dispute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='blizzgame.dispute'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('purchase_intent', "Intention d'achat"), ('new_message', 'Nouveau message'), ('transaction_update', 'Mise à jour de transaction'), ('system', 'Notification système'), ('private_message', 'Message privé'), ('group_message', 'Message de groupe'), ('group_invite', 'Invitation de groupe'), ('friend_request', "Demande d'ami"), ('friend_accept', 'Amitié acceptée'), ('dispute_created', 'Litige créé'), ('dispute_resolved', 'Litige résolu'), ('dispute_message', 'Message de litige')], max_length=20),
        ),
    ]
