# Generated by Django 5.2.5 on 2025-08-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blizzgame', '0030_notification_dispute_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Délai limite pour résolution (72h par défaut)', null=True),
        ),
    ]
