# Generated by Django 5.2.5 on 2025-08-29 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blizzgame', '0032_alter_disputemessage_is_internal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=3)),
                ('target_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['base_currency', 'target_currency'], name='blizzgame_e_base_cu_958246_idx'), models.Index(fields=['last_updated'], name='blizzgame_e_last_up_b0cf2d_idx')],
                'unique_together': {('base_currency', 'target_currency')},
            },
        ),
        migrations.CreateModel(
            name='UserCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_currency', models.CharField(choices=[('EUR', 'Euro (€)'), ('XOF', 'Franc CFA Ouest (FCFA)'), ('XAF', 'Franc CFA Central (FCFA)'), ('GNF', 'Franc Guinéen (GNF)'), ('USD', 'Dollar Américain ($)'), ('GBP', 'Livre Sterling (£)'), ('CAD', 'Dollar Canadien (CAD)')], default='EUR', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='currency_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
