# Generated by Django 5.2.5 on 2025-09-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blizzgame', '0041_emailverification_twofactorauth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twofactorauth',
            name='backup_codes',
        ),
        migrations.RemoveField(
            model_name='twofactorauth',
            name='secret_key',
        ),
        migrations.AddField(
            model_name='twofactorauth',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='twofactorauth',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='twofactorauth',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='twofactorauth',
            name='verification_method',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='email', max_length=10),
        ),
    ]
