# Generated by Django 5.2.5 on 2025-09-07 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blizzgame', '0047_add_reset_code_to_passwordreset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_user',
        ),
    ]
