# Generated by Django 5.2.5 on 2025-09-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blizzgame', '0048_remove_id_user_from_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercurrency',
            name='preferred_currency',
            field=models.CharField(choices=[('EUR', 'Euro (€)'), ('USD', 'Dollar Américain ($)'), ('GBP', 'Livre Sterling (£)'), ('XOF', 'Franc CFA Ouest (FCFA)'), ('XAF', 'Franc CFA Central (FCFA)'), ('GNF', 'Franc Guinéen (GNF)'), ('NGN', 'Naira Nigérian (₦)'), ('GHS', 'Cedi Ghanéen (₵)'), ('MAD', 'Dirham Marocain (د.م.)'), ('DZD', 'Dinar Algérien (د.ج)'), ('TND', 'Dinar Tunisien (د.ت)'), ('EGP', 'Livre Égyptienne (ج.م)'), ('JPY', 'Yen Japonais (¥)'), ('CNY', 'Yuan Chinois (¥)'), ('INR', 'Roupie Indienne (₹)'), ('KRW', 'Won Sud-Coréen (₩)'), ('THB', 'Baht Thaïlandais (฿)'), ('VND', 'Dong Vietnamien (₫)'), ('IDR', 'Roupie Indonésienne (Rp)'), ('PHP', 'Peso Philippin (₱)'), ('MYR', 'Ringgit Malaisien (RM)'), ('SGD', 'Dollar Singapourien (S$)'), ('BRL', 'Real Brésilien (R$)'), ('MXN', 'Peso Mexicain ($)'), ('ARS', 'Peso Argentin ($)'), ('CLP', 'Peso Chilien ($)'), ('COP', 'Peso Colombien ($)'), ('PEN', 'Sol Péruvien (S/)'), ('UYU', 'Peso Uruguayen ($)'), ('VES', 'Bolívar Vénézuélien (Bs)'), ('CAD', 'Dollar Canadien (CAD)'), ('AUD', 'Dollar Australien (A$)'), ('NZD', 'Dollar Néo-Zélandais (NZ$)'), ('CHF', 'Franc Suisse (CHF)'), ('SEK', 'Couronne Suédoise (kr)'), ('NOK', 'Couronne Norvégienne (kr)'), ('DKK', 'Couronne Danoise (kr)'), ('PLN', 'Zloty Polonais (zł)'), ('CZK', 'Couronne Tchèque (Kč)'), ('HUF', 'Forint Hongrois (Ft)'), ('RON', 'Leu Roumain (lei)'), ('BGN', 'Lev Bulgare (лв)'), ('HRK', 'Kuna Croate (kn)'), ('RSD', 'Dinar Serbe (дин)'), ('UAH', 'Hryvnia Ukrainienne (₴)'), ('RUB', 'Rouble Russe (₽)'), ('TRY', 'Livre Turque (₺)')], default='EUR', max_length=3),
        ),
    ]
