# Generated by Django 5.2.5 on 2025-09-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blizzgame', '0050_add_payment_verification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_in_transaction',
            field=models.BooleanField(default=False),
        ),
    ]
