# Generated by Django 5.2.5 on 2025-09-10 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blizzgame', '0051_add_is_in_transaction_field'),
    ]

    operations = [
    ]
