# Generated by Django 5.2.5 on 2025-09-12 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blizzgame', '0058_add_encrypted_fields'),
        ('blizzgame', '0057_add_notification_grouping_fields'),
        ('blizzgame', '0059_migrate_to_encrypted_fields'),
    ]

    operations = [
    ]
