# Generated by Django 5.2.5 on 2025-09-12 14:17

import blizzgame.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blizzgame', '0060_merge_20250912_0530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['is_read', '-created_at']},
        ),
        migrations.AlterField(
            model_name='sellerpaymentinfo',
            name='encrypted_account_holder_name',
            field=blizzgame.encrypted_fields.EncryptedCharField(blank=True, help_text=' (Chiffré automatiquement) (Chiffré automatiquement)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellerpaymentinfo',
            name='encrypted_account_number',
            field=blizzgame.encrypted_fields.EncryptedCharField(blank=True, help_text=' (Chiffré automatiquement) (Chiffré automatiquement)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sellerpaymentinfo',
            name='encrypted_bank_name',
            field=blizzgame.encrypted_fields.EncryptedCharField(blank=True, help_text=' (Chiffré automatiquement) (Chiffré automatiquement)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellerpaymentinfo',
            name='encrypted_card_holder_name',
            field=blizzgame.encrypted_fields.EncryptedCharField(blank=True, help_text=' (Chiffré automatiquement) (Chiffré automatiquement)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellerpaymentinfo',
            name='encrypted_card_number',
            field=blizzgame.encrypted_fields.EncryptedCharField(blank=True, help_text=' (Chiffré automatiquement) (Chiffré automatiquement)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sellerpaymentinfo',
            name='encrypted_iban',
            field=blizzgame.encrypted_fields.EncryptedCharField(blank=True, help_text=' (Chiffré automatiquement) (Chiffré automatiquement)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sellerpaymentinfo',
            name='encrypted_phone_number',
            field=blizzgame.encrypted_fields.EncryptedCharField(blank=True, help_text=' (Chiffré automatiquement) (Chiffré automatiquement)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sellerpaymentinfo',
            name='encrypted_swift_code',
            field=blizzgame.encrypted_fields.EncryptedCharField(blank=True, help_text=' (Chiffré automatiquement) (Chiffré automatiquement)', max_length=20, null=True),
        ),
    ]
