# Generated by Django 5.2.5 on 2025-09-17 19:20

import blizzgame.encrypted_fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blizzgame', '0063_profile_payout_country_profile_payout_operator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='dispute',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='blizzgame.dispute'),
        ),
        migrations.AddField(
            model_name='chat',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Message texte'), ('image', 'Image'), ('file', 'Fichier')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='blizzgame.transaction'),
        ),
        migrations.AlterField(
            model_name='sellerpaymentinfo',
            name='encrypted_account_holder_name',
            field=blizzgame.encrypted_fields.EncryptedCharField(blank=True, help_text=' (Chiffré automatiquement) (Chiffré automatiquement)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellerpaymentinfo',
            name='encrypted_account_number',
            field=blizzgame.encrypted_fields.EncryptedCharField(blank=True, help_text=' (Chiffré automatiquement) (Chiffré automatiquement)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sellerpaymentinfo',
            name='encrypted_bank_name',
            field=blizzgame.encrypted_fields.EncryptedCharField(blank=True, help_text=' (Chiffré automatiquement) (Chiffré automatiquement)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellerpaymentinfo',
            name='encrypted_card_holder_name',
            field=blizzgame.encrypted_fields.EncryptedCharField(blank=True, help_text=' (Chiffré automatiquement) (Chiffré automatiquement)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellerpaymentinfo',
            name='encrypted_card_number',
            field=blizzgame.encrypted_fields.EncryptedCharField(blank=True, help_text=' (Chiffré automatiquement) (Chiffré automatiquement)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sellerpaymentinfo',
            name='encrypted_iban',
            field=blizzgame.encrypted_fields.EncryptedCharField(blank=True, help_text=' (Chiffré automatiquement) (Chiffré automatiquement)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sellerpaymentinfo',
            name='encrypted_phone_number',
            field=blizzgame.encrypted_fields.EncryptedCharField(blank=True, help_text=' (Chiffré automatiquement) (Chiffré automatiquement)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sellerpaymentinfo',
            name='encrypted_swift_code',
            field=blizzgame.encrypted_fields.EncryptedCharField(blank=True, help_text=' (Chiffré automatiquement) (Chiffré automatiquement)', max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('dispute__isnull', True), ('transaction__isnull', False)), models.Q(('dispute__isnull', False), ('transaction__isnull', True)), _connector='OR'), name='chat_has_transaction_or_dispute'),
        ),
    ]
