# Generated by Django 5.2.5 on 2025-01-27 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blizzgame', '0066_add_original_amount_to_payoutrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='blizzgame.order'),
        ),
    ]
