"""
Django settings for socialgame project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'drink-nursery-show-mud.trycloudflare.com',
    'testserver',  # Pour les tests Django
    '.onrender.com',  # Pour Render
    '*',  # Temporaire pour le déploiement
]

# Configuration CSRF pour CinetPay
CSRF_TRUSTED_ORIGINS = [
    'https://checkout.cinetpay.com',
    'https://api-checkout.cinetpay.com',
    'https://cuddly-bassoon-xa8c.onrender.com',
    'https://blizz-web-service.onrender.com',
    'https://*.onrender.com',
    'http://localhost:8000',
]

# Ajouter dynamiquement le hostname Render si disponible
_render_host = config('RENDER_EXTERNAL_HOSTNAME', default='').strip()
if _render_host:
    origin = f"https://{_render_host}"
    if origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(origin)
# Django derrière proxy (Render) : reconnaître HTTPS et host forwardés
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

# Cookies sécurisés en prod (HTTPS)
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'

# Configuration Django Sites
SITE_ID = 1


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'blizzgame',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'cloudinary',
    'cloudinary_storage',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Pour servir les fichiers statiques sur Render
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'blizzgame.middleware.BanCheckMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'socialgame.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'socialgame.wsgi.application'
ASGI_APPLICATION = 'socialgame.asgi.application'

# Configuration Channels avec Redis
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [config('REDIS_URL', default='redis://localhost:6379')],
        },
    },
}

# Configuration du cache Redis pour Render - Optimisée pour faible trafic
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': config('REDIS_URL', default='redis://localhost:6379'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 10,  # Réduit de 50 à 10 pour faible trafic
                'retry_on_timeout': True,
                'socket_keepalive': True,
                'socket_keepalive_options': {
                    1: 1,  # TCP_KEEPIDLE
                    2: 1,  # TCP_KEEPINTVL
                    3: 3,  # TCP_KEEPCNT
                },
            },
            # TTL par défaut pour le cache (1 heure)
            'TIMEOUT': 3600,
            # Compression pour réduire l'utilisation mémoire
            'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
            # Ne pas faire planter l'app si Redis est temporairement indisponible
            'IGNORE_EXCEPTIONS': True,
        },
        'KEY_PREFIX': 'blizz',
        'VERSION': 1,
    }
}

# Configuration du rate limiting
RATELIMIT_USE_CACHE = 'default'
RATELIMIT_ENABLE = True


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Configuration de la base de données pour Render
try:
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.parse(
            config('DATABASE_URL', default='sqlite:///db.sqlite3'),
            conn_max_age=600,  # Pool de connexions
            conn_health_checks=True,  # Vérification de santé
        )
    }
    
    # Configuration SSL : désactivé pour connexions internes (Sevalla), requis pour externes (Render, Supabase)
    if 'postgres' in DATABASES['default']['ENGINE']:
        db_host = DATABASES['default'].get('HOST', '') or ''
        # Connexions internes (Kubernetes/Sevalla) : pas de SSL
        is_internal = 'svc.cluster' in db_host or 'cluster.local' in db_host
        ssl_mode = config('DATABASE_SSL_MODE', default='disable' if is_internal else 'require')
        DATABASES['default']['OPTIONS'] = {
            'sslmode': ssl_mode,
            'connect_timeout': 10,
        }
        
except ImportError:
    # Fallback pour le développement local
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        'OPTIONS': {
            'max_similarity': 0.7,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    # Validateur personnalisé pour BLIZZ avec règles de sécurité renforcées
    {
        'NAME': 'blizzgame.validators.BlizzPasswordValidator',
    },
]
SITE_ID = 1


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Configuration de l'internationalisation
LANGUAGES = [
    ('fr', 'Français'),
    ('en', 'English'),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Configuration pour les fichiers statiques sur Render
# Changé de CompressedManifestStaticFilesStorage à CompressedStaticFilesStorage pour éviter les erreurs 500
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

# Media storage: Force Cloudinary in production
CLOUDINARY_URL = config('CLOUDINARY_URL', default='')

# Configure Cloudinary first if URL is present
if CLOUDINARY_URL:
    # Parse CLOUDINARY_URL and configure
    import cloudinary
    import cloudinary.uploader
    import cloudinary.api
    import re
    
    match = re.search(r'cloudinary://([^:]+):([^@]+)@(.+)', CLOUDINARY_URL)
    if match:
        api_key, api_secret, cloud_name = match.groups()
        cloudinary.config(
            cloud_name=cloud_name,
            api_key=api_key,
            api_secret=api_secret,
            secure=True
        )

# Set storage settings - Force Cloudinary in production
if CLOUDINARY_URL:
    # Production: use Cloudinary
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
    MEDIA_URL = '/media/'  # Cloudinary will override this
    
    # Force Django to use our storage by overriding the default_storage import
    import django.core.files.storage
    from cloudinary_storage.storage import MediaCloudinaryStorage
    django.core.files.storage.default_storage = MediaCloudinaryStorage()
else:
    # Development: use filesystem
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Legacy settings for compatibility
USE_CLOUDINARY = bool(CLOUDINARY_URL)

# Configuration CinetPay
CINETPAY_API_KEY = config('CINETPAY_API_KEY')
CINETPAY_SITE_ID = config('CINETPAY_SITE_ID')
CINETPAY_SECRET_KEY = config('CINETPAY_SECRET_KEY')

# Modes test CinetPay - Séparés pour gaming et dropshipping
CINETPAY_GAMING_TEST_MODE = config('CINETPAY_GAMING_TEST_MODE', default=False, cast=bool)  # Désactivé pour gaming
CINETPAY_DROPSHIPPING_TEST_MODE = config('CINETPAY_DROPSHIPPING_TEST_MODE', default=False, cast=bool)  # Désactivé pour dropshipping

CINETPAY_TEST_MODE = False  # Forcé à False pour désactiver le mode test global

# URL de base pour les callbacks CinetPay
# En production, utiliser l'URL Render, en local utiliser localhost
if config('ENVIRONMENT', default='production') == 'production':
    BASE_URL = 'https://blizz-web-service.onrender.com'
else:
    BASE_URL = config('BASE_URL', default='http://localhost:8000')

# Configuration email Gmail SMTP
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Configuration de vérification email
EMAIL_VERIFICATION_REQUIRED = True
EMAIL_VERIFICATION_EXPIRE_HOURS = 24

# Payment Timeout Settings
PAYMENT_TIMEOUT_MINUTES = 30  # Payments pending for more than 30 minutes will be considered abandoned
TRANSACTION_CLEANUP_INTERVAL_MINUTES = 5  # How often to run cleanup (in minutes)

# Configuration Pusher
PUSHER_APP_ID = '2048748'
PUSHER_KEY = '6c5ea23d443700ec8467'
PUSHER_SECRET = '90b110685b3e2349c93f'
PUSHER_CLUSTER = 'eu'

# Webhook secret pour nettoyage automatique
WEBHOOK_SECRET = config('WEBHOOK_SECRET', default='blizz-game-cleanup-2024')

# Configuration Shopify - DÉSACTIVÉ (pas nécessaire pour le moment)
# SHOPIFY_SHOP_NAME = config('SHOPIFY_SHOP_NAME', default='')
# SHOPIFY_ACCESS_TOKEN = config('SHOPIFY_ACCESS_TOKEN', default='')
# SHOPIFY_SHOP_URL = config('SHOPIFY_SHOP_URL', default='')

# Configuration de logging optimisée pour Railway/Render (console uniquement)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',  # Seulement les erreurs
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'ERROR',  # Désactiver les logs SQL en production
            'propagate': False,
        },
    },
}
# SHOPIFY_WEBHOOK_SECRET = config('SHOPIFY_WEBHOOK_SECRET', default='')  # Désactivé