# Generated by Django 5.2.5 on 2025-08-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blizzgame', '0027_profile_appreciation_count_profile_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='score',
            field=models.IntegerField(default=0, help_text='Score basé sur les appréciations des Highlights'),
        ),
    ]
