# Generated by Django 5.2.5 on 2025-08-28 11:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blizzgame', '0028_alter_profile_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('invalid_account', 'Compte gaming invalide'), ('wrong_data', 'Données incorrectes'), ('no_response', 'Vendeur ne répond pas'), ('account_recovered', 'Compte récupéré par le propriétaire original'), ('fake_screenshots', "Captures d'écran falsifiées"), ('other', 'Autre motif')], max_length=50)),
                ('description', models.TextField(help_text='Description détaillée du problème')),
                ('evidence', models.JSONField(default=dict, help_text='Preuves uploadées (screenshots, logs, etc.)')),
                ('chat_logs', models.TextField(blank=True, help_text='Logs de chat sauvegardés automatiquement')),
                ('status', models.CharField(choices=[('pending', "En attente d'examen"), ('investigating', 'Enquête en cours'), ('awaiting_evidence', 'En attente de preuves'), ('resolved_buyer', "Résolu en faveur de l'acheteur"), ('resolved_seller', 'Résolu en faveur du vendeur'), ('closed', 'Fermé sans suite')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('urgent', 'Urgente')], default='medium', max_length=10)),
                ('admin_notes', models.TextField(blank=True, help_text='Notes internes pour les administrateurs')),
                ('resolution', models.CharField(blank=True, choices=[('refund', 'Remboursement acheteur'), ('payout', 'Paiement vendeur'), ('partial_refund', 'Remboursement partiel'), ('no_action', 'Aucune action')], max_length=20)),
                ('resolution_details', models.TextField(blank=True, help_text='Détails de la résolution')),
                ('disputed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(help_text='Délai limite pour résolution (72h par défaut)')),
                ('response_time_hours', models.IntegerField(blank=True, help_text='Temps de première réponse en heures', null=True)),
                ('resolution_time_hours', models.IntegerField(blank=True, help_text='Temps total de résolution en heures', null=True)),
                ('assigned_admin', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_disputes', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opened_disputes', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='blizzgame.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Message visible uniquement par les admins')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='blizzgame.dispute')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['status', 'priority'], name='blizzgame_d_status_fc06c4_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['assigned_admin', 'status'], name='blizzgame_d_assigne_736f9c_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['created_at'], name='blizzgame_d_created_68f273_idx'),
        ),
    ]
