# Generated by Django 5.2.5 on 2025-08-28 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blizzgame', '0031_alter_dispute_deadline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='disputemessage',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='Message visible seulement par les admins'),
        ),
        migrations.CreateModel(
            name='DisputeInformationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('text_response', 'Réponse textuelle'), ('screenshot', "Capture d'écran"), ('document', 'Document/Preuve')], max_length=20)),
                ('question', models.TextField(help_text="Question ou demande d'information")),
                ('response_text', models.TextField(blank=True, help_text="Réponse textuelle de l'utilisateur")),
                ('response_file', models.FileField(blank=True, help_text='Fichier uploadé en réponse', upload_to='dispute_responses/')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('responded', 'Répondu'), ('expired', 'Expiré')], default='pending', max_length=20)),
                ('deadline', models.DateTimeField(help_text='Délai de réponse (24h par défaut)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='information_requests', to='blizzgame.dispute')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
