# Generated by Django 5.2.5 on 2025-08-29 17:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blizzgame', '0033_exchangerate_usercurrency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('inappropriate', 'Contenu inapproprié'), ('spam', 'Spam'), ('harassment', 'Harcèlement'), ('violence', 'Violence'), ('hate_speech', 'Discours de haine'), ('copyright', "Violation de droits d'auteur"), ('other', 'Autre')], max_length=20)),
                ('description', models.TextField(help_text='Description détaillée du problème')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('reviewing', "En cours d'examen"), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('resolved', 'Résolu')], default='pending', max_length=20)),
                ('moderator_notes', models.TextField(blank=True, help_text='Notes du modérateur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('highlight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='blizzgame.highlight')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reports', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('reporter', 'highlight')},
            },
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('approve', 'Approuver'), ('reject', 'Rejeter'), ('remove', 'Supprimer'), ('warn_user', "Avertir l'utilisateur"), ('suspend_user', "Suspendre l'utilisateur"), ('ban_user', "Bannir l'utilisateur")], max_length=20)),
                ('reason', models.TextField(help_text="Raison de l'action")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='blizzgame.contentreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserModerationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('warned', 'Averti'), ('suspended', 'Suspendu'), ('banned', 'Banni')], default='active', max_length=20)),
                ('warnings_count', models.IntegerField(default=0)),
                ('suspension_until', models.DateTimeField(blank=True, null=True)),
                ('banned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_status', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
