# Generated by Django 5.2.5 on 2025-08-29 18:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blizzgame', '0034_contentreport_moderationaction_usermoderationstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderationaction',
            name='report',
        ),
        migrations.RemoveField(
            model_name='moderationaction',
            name='moderator',
        ),
        migrations.RemoveField(
            model_name='usermoderationstatus',
            name='last_action_by',
        ),
        migrations.RemoveField(
            model_name='usermoderationstatus',
            name='user',
        ),
        migrations.AddField(
            model_name='highlightview',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='True if user watched the full highlight'),
        ),
        migrations.CreateModel(
            name='UserFeedProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('last_position', models.IntegerField(default=0, help_text='Position dans le feed (index)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_viewed_highlight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blizzgame.highlight')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feed_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ContentReport',
        ),
        migrations.DeleteModel(
            name='ModerationAction',
        ),
        migrations.DeleteModel(
            name='UserModerationStatus',
        ),
    ]
