# Generated by Django 5.2.5 on 2025-08-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blizzgame', '0036_remove_highlightview_is_completed_groupmessage_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_on_sale',
            field=models.BooleanField(default=True),
        ),
    ]
