# Generated by Django 5.2.5 on 2025-09-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blizzgame', '0043_alter_emailverification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='last_email_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
