# Generated by Django 5.2.5 on 2025-09-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blizzgame', '0044_add_last_email_sent_to_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
