# Generated by Django 5.2.5 on 2025-09-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blizzgame', '0049_add_extended_currencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerpaymentinfo',
            name='last_verification_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerpaymentinfo',
            name='verification_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sellerpaymentinfo',
            name='verification_failed_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
