# Generated by Django 5.2.5 on 2025-09-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blizzgame', '0052_auto_20250910_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message_count',
            field=models.PositiveIntegerField(default=1, help_text='Nombre de messages groupés'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender_username',
            field=models.CharField(blank=True, help_text="Nom d'utilisateur de l'expéditeur des messages groupés", max_length=150),
        ),
    ]
