# Generated by Django 5.2.5 on 2025-09-16 10:55

import blizzgame.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blizzgame', '0061_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_username_change',
            field=models.DateTimeField(blank=True, help_text='Date du dernier changement de pseudo', null=True),
        ),
        migrations.AlterField(
            model_name='sellerpaymentinfo',
            name='encrypted_account_holder_name',
            field=blizzgame.encrypted_fields.EncryptedCharField(blank=True, help_text=' (Chiffré automatiquement) (Chiffré automatiquement)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellerpaymentinfo',
            name='encrypted_account_number',
            field=blizzgame.encrypted_fields.EncryptedCharField(blank=True, help_text=' (Chiffré automatiquement) (Chiffré automatiquement)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sellerpaymentinfo',
            name='encrypted_bank_name',
            field=blizzgame.encrypted_fields.EncryptedCharField(blank=True, help_text=' (Chiffré automatiquement) (Chiffré automatiquement)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellerpaymentinfo',
            name='encrypted_card_holder_name',
            field=blizzgame.encrypted_fields.EncryptedCharField(blank=True, help_text=' (Chiffré automatiquement) (Chiffré automatiquement)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellerpaymentinfo',
            name='encrypted_card_number',
            field=blizzgame.encrypted_fields.EncryptedCharField(blank=True, help_text=' (Chiffré automatiquement) (Chiffré automatiquement)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sellerpaymentinfo',
            name='encrypted_iban',
            field=blizzgame.encrypted_fields.EncryptedCharField(blank=True, help_text=' (Chiffré automatiquement) (Chiffré automatiquement)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sellerpaymentinfo',
            name='encrypted_phone_number',
            field=blizzgame.encrypted_fields.EncryptedCharField(blank=True, help_text=' (Chiffré automatiquement) (Chiffré automatiquement)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sellerpaymentinfo',
            name='encrypted_swift_code',
            field=blizzgame.encrypted_fields.EncryptedCharField(blank=True, help_text=' (Chiffré automatiquement) (Chiffré automatiquement)', max_length=20, null=True),
        ),
    ]
