# Generated by Django 5.2.5 on 2025-09-17 13:32

import blizzgame.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blizzgame', '0062_profile_last_username_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payout_country',
            field=models.CharField(blank=True, help_text='Code pays pour les payouts (ex: CI, SN, ML)', max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='payout_operator',
            field=models.CharField(blank=True, help_text='Opérateur mobile pour les payouts', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='payout_phone',
            field=models.CharField(blank=True, help_text='Numéro de téléphone pour les payouts', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='payout_verified',
            field=models.BooleanField(default=False, help_text='Informations de payout vérifiées'),
        ),
        migrations.AlterField(
            model_name='sellerpaymentinfo',
            name='encrypted_account_holder_name',
            field=blizzgame.encrypted_fields.EncryptedCharField(blank=True, help_text=' (Chiffré automatiquement) (Chiffré automatiquement)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellerpaymentinfo',
            name='encrypted_account_number',
            field=blizzgame.encrypted_fields.EncryptedCharField(blank=True, help_text=' (Chiffré automatiquement) (Chiffré automatiquement)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sellerpaymentinfo',
            name='encrypted_bank_name',
            field=blizzgame.encrypted_fields.EncryptedCharField(blank=True, help_text=' (Chiffré automatiquement) (Chiffré automatiquement)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellerpaymentinfo',
            name='encrypted_card_holder_name',
            field=blizzgame.encrypted_fields.EncryptedCharField(blank=True, help_text=' (Chiffré automatiquement) (Chiffré automatiquement)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellerpaymentinfo',
            name='encrypted_card_number',
            field=blizzgame.encrypted_fields.EncryptedCharField(blank=True, help_text=' (Chiffré automatiquement) (Chiffré automatiquement)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sellerpaymentinfo',
            name='encrypted_iban',
            field=blizzgame.encrypted_fields.EncryptedCharField(blank=True, help_text=' (Chiffré automatiquement) (Chiffré automatiquement)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sellerpaymentinfo',
            name='encrypted_phone_number',
            field=blizzgame.encrypted_fields.EncryptedCharField(blank=True, help_text=' (Chiffré automatiquement) (Chiffré automatiquement)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sellerpaymentinfo',
            name='encrypted_swift_code',
            field=blizzgame.encrypted_fields.EncryptedCharField(blank=True, help_text=' (Chiffré automatiquement) (Chiffré automatiquement)', max_length=20, null=True),
        ),
    ]
